name: Backend Test
run-name: ${{ github.actor }} is testing backend working or not 🚀
on: [push]

jobs:
  build:
    name: FrontEnd Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: cd frontend/pfw_chatbot/ && npm install
      - name: Test
        run: npm test