name: Chatbot Testing
run-name: ${{ github.actor }} is testing bot is working or not
on: [ push, workflow_dispatch ]

jobs:
  ui_test:
    name: FrontEnd Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: cd frontend/pfw_chatbot/ && npm install
      - name: Test
        run: cd frontend/pfw_chatbot/ && npm test || true

  backend_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9", "3.10" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          cat requirements.txt | xargs -n 1 pip install || true
      - name: Analysing the code with pylint
        run: |
          pylint --rcfile=.pylintrc $(git ls-files '*.py')
          pylint_exit_code=$?
          if [ $pylint_exit_code -gt 5 ]; then
            echo "Pylint passed with a score greater than 5."
          exit 0
          else
            echo "Pylint failed with a score of 5 or less."
            exit 1
          fi

  deploy:
    needs: [ui_test, backend_test]
    runs-on: ubuntu-latest
    steps:
        - name: Success
          run: echo "Success"